Yenda/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app.urls")),
    path('reservation/', include('reservation_system.urls')),
    path('api-token-auth/', obtain_auth_token), #gives us access to token auth

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from .utils import  hash_trip_id, decode_hashed_trip_id

app_name = 'app'

urlpatterns = [

   path("register-user", views.register_user, name="register-user"),
   path("login", views.login_register, name="login"),
   path("logout", views.logoutUser, name="logout"),
   path("", views.dashboard, name="dashboard"),
   path("popular-places", views.popular_places, name="popular places"),
   path('search/', views.search, name='search'),
   path('update_bookmark_status/', views.update_bookmark_status, name='update_bookmark_status'),
   path('bookmarked/', views.bookmarked_trips, name='bookmarked_trips'),
   path('select_tickets/<uuid:trip_id>/', views.select_tickets, name='select_tickets'),
   path('enter_passenger_details/<uuid:trip_id>/', views.enter_passenger_details, name='enter_passenger_details'),
   path('ticket_confirmation/<uuid:trip_id>/', views.ticket_confirmation, name='ticket_confirmation'),
   path('ticket_cancel', views.cancel_confirmation, name ='ticket-cancel'),
   path('ticket_success/<uuid:trip_id>/', views.ticket_success, name='ticket_success'),
   path('tickets', views.tickets, name='tickets'),
   path('update_ticket_active_status/<int:ticket_id>/', views.update_ticket_active_status, name='update_ticket_active_status'),
   path('previous-tickets', views.previous_tickets, name='previous-tickets'),
   path('account-details',views.user_account_details, name = 'account-details'),
   path('about-&-info', views.about_info, name = 'about-info'),
   path('change-name', views.change_name, name='change-name'),
   path('change-profile picture', views.change_profilepic, name='change-profile_pic'),

    
   #Courier Service
   path('courier-search/', views.courier_search, name='courier-search' ),
   path('enter-package-details/', views.enter_package_details, name = 'enter-package-details'),
   path('superuser/messages/', views.superuser_messages, name='superuser_messages'),
   path('inbox/', views.inbox_list, name='inbox-list'),
   path('conversation/<int:sender_id>/', views.conversation, name='conversation'),
   path('check-new-messages/', views.check_new_messages, name='check_new_messages'),
   path('mark-messages-as-read/', views.mark_messages_as_read, name='mark_messages_as_read'),
   path('package-payment/', views.package_payment, name='package-payment'),
   path('courier-receipts/', views.courier_receipts, name='courier-receipts'),
   path('edit/<int:message_id>/', views.edit_message, name='edit_message'),
   path('delete/<int:message_id>/', views.delete_message, name='delete_message'),
   path('toggle_active/<int:receipt_id>/', views.toggle_active, name='toggle_active'),
   path('courier-done/', views.fulfilled_receipts, name='courier-done'),

   
   #Customer Service
   #path('customer-service/message/<int:sender_id>/', views.customer_service_message, name='customer_service_message'),
   path('customer-service/inbox/', views.customer_service_inbox, name='customer_service_inbox'),
   path('submit_message/<int:sender_id>/', views.submit_message, name='submit_message'),


   #Suggestions
   path('submit-suggestion/', views.submit_suggestion, name='submit_suggestion'),


   #Forgot Password
   path('reset_password/',
   auth_views.PasswordResetView.as_view(
      template_name="../templates/registration/reset_password.html",
      success_url = reverse_lazy("app:password_reset_done")
   ), name='reset_password'),

   path('reset_password_sent/',
    auth_views.PasswordResetDoneView.as_view(
    ), name="password_reset_done"),

   path('reset/<uidb64>/<token>/',
    auth_views.PasswordResetConfirmView.as_view(
      template_name="registration/password_reset_confirm.html",
      success_url = reverse_lazy("app:password_reset_complete")
  ), name='password_reset_confirm'),

   path('reset_password_complete/',
    auth_views.PasswordResetCompleteView.as_view(
      template_name="registration/password_reset_complete.html"
    ), name="password_reset_complete"),


# DRF URLS
   path('ticket-confirmation/<uuid:trip_id>', views.TicketConfirmationAPIView.as_view(), name='ticket-confirmation'),

]  

# Add the following line to serve media files during development
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservation_system/urls.py
# reservation_system/urls.py

from django.urls import path
from . import views


app_name = 'reservation_system'

urlpatterns = [
    path('register/', views.register, name='register-bus'),  # Note the trailing slash in the URL pattern
    path('', views.bus_operator_dashboard, name='bus_operator_dashboard'),
    path('Detail Entry', views.detail_entry, name="detail_entry"), 
    path('qrcode-scanner/', views.qr_code_scanner, name='qrcode-scanner'),
    path('verify-ticket/', views.verify_ticket, name='verify_ticket'),
    

    #DRF URLS
    path('bus-operator-registration/', views.BusOperatorRegistrationAPIView.as_view(), name='bus_operator_registration'),
    path('trip-schedule-entry/', views.TripScheduleAPIView.as_view(), name='trip_detail_entry'),

]

reservation_system/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from app.models import User
from django.utils import timezone
import uuid
import qrcode
from io import BytesIO
from django.core.files.base import ContentFile



class ReservationSystemUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='reservationsystemuser')
    email = models.EmailField(null=False, default="")
    total_seats = models.IntegerField(default=0)
    rows = models.IntegerField(default=0)
    columns = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.user}'

class TripSchedule(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, null=False)
    bus_operator = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    driver = models.CharField(max_length=100, default="")
    origin = models.CharField(max_length=100)
    destination = models.CharField(max_length=100)
    departure_date = models.DateField(default=timezone.now)
    departure_time = models.TimeField(default=timezone.now)
    estimated_arrival_time = models.TimeField(default=timezone.now)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    bookmarked = models.BooleanField(default=False)
    
    def __str__(self):
            return f'{self.bus_operator}'

class BuyerDetails(models.Model):
    buyer = models.ForeignKey(User, on_delete=models.CASCADE)
    trip = models.ForeignKey(TripSchedule, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, default="")
    phonenumber = models.CharField(max_length=15, default="")
    confirmed = models.BooleanField(default=False)  # Add this field

class Tickets(models.Model):
    buyer_name = models.ForeignKey(User, on_delete=models.CASCADE)
    buyer_trip = models.ForeignKey(TripSchedule, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, null=True, blank=True)  # Track payment status (e.g., new, paid, failed)
    timestamp = models.DateTimeField(auto_now_add=True)


class Ticket(models.Model):
    ticket_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    buyer = models.ForeignKey(User, on_delete=models.CASCADE)
    trip = models.ForeignKey(TripSchedule, on_delete=models.CASCADE)
    passenger_name = models.CharField(max_length=15, default="", null=True)
    passenger_phonenumber = models.CharField(max_length=15)
    confirmed = models.BooleanField(default=False)
    active = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_used = models.BooleanField(default=False)
    ticket_no = models.CharField(max_length=100, default="")
    
    #QR Code
    qr_code = models.ImageField(upload_to='qr_codes/', blank=True, null=True)

    def save_qr_code(self, ticket_number):
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        qr.add_data(ticket_number)
        qr.make(fit=True)

        qr_code_io = BytesIO()
        qr.make_image(fill_color="black", back_color="white").save(qr_code_io, format='PNG')

        self.qr_code.save(f'qr_code_{self.id}.png', ContentFile(qr_code_io.getvalue()), save=False)
        super().save()

    def __str__(self):
        return f"Ticket ID: {self.ticket_id}, Passenger: {self.passenger_name}, Trip: {self.trip}"



# ===== COURIER SERVICES =====
class PackageDetails(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    item_name = models.CharField(max_length=100, default="")
    length =  models.DecimalField(max_digits=8, decimal_places=2)
    width =   models.DecimalField(max_digits=8, decimal_places=2)
    height = models.DecimalField(max_digits=8, decimal_places=2)
    weight = models.DecimalField(max_digits=8, decimal_places=2)
    item_quantity = models.IntegerField(default=1)
    fragile_item = models.BooleanField(default=False, null=True, blank=True)
    item_category = models.CharField(max_length=100, default="")
    item_description = models.TextField()

class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_messages')
    recipient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_messages')
    subject = models.CharField(max_length=100)
    body = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.subject} - From: {self.sender.username} To: {self.recipient.username}"

class PackagePayment(models.Model):
    initiator = models.ForeignKey(User, on_delete=models.CASCADE,null=True, related_name='package_payment')
    pesapal_transaction_tracking_id = models.CharField(max_length=100, default='', null=True, blank=True)
    package_id = models.IntegerField( default=0)
    courier = models.CharField(max_length=20, default="")
    sender_name = models.CharField(max_length=20, default="")
    sender_number = models.CharField(max_length=20, default="")
    receiver_name =  models.CharField(max_length=20, default="")
    receiver_number =models.CharField(max_length=20, default="")
    amount = models.FloatField(default=0)
    status = models.CharField(max_length=20, null=True, blank=True)  # Track payment status (e.g., new, paid, failed)
    is_active = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    qr_code = models.ImageField(upload_to='courier receipt-qr_codes/', blank=True, null=True)

    def save_qr_code(self, package_id):
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        qr.add_data(package_id)
        qr.make(fit=True)

        qr_code_io = BytesIO()
        qr.make_image(fill_color="black", back_color="white").save(qr_code_io, format='PNG')

        self.qr_code.save(f'qr_code_{self.id}.png', ContentFile(qr_code_io.getvalue()), save=False)
        super().save()


class CustomerService(models.Model):
    sender = models.ForeignKey(User, related_name='customer_service_sent_messages', on_delete=models.CASCADE, default=None)
    receiver = models.ForeignKey(User, related_name='customer_service_received_messages', on_delete=models.CASCADE, default=None)
    content = models.TextField(default='')
    read = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"From {self.sender.username} to {self.receiver.username}: {self.content}"


class Suggestion(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)  # Optional user association
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)  # Automatic timestamp
  
    def __str__(self):
        return f"{self.description} - {self.user}"




































    

    """
    # New fields to store the number of rows and columns
    rows = models.IntegerField(default=0)
    columns = models.IntegerField(default=0)

# models.py
class Seat(models.Model):
    bus_operator = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    trip_schedule = models.ForeignKey(TripSchedule, on_delete=models.CASCADE, null=True)
    booked_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='booked_seats', null=True)
    seat_number = models.CharField(max_length=10)
    column = models.IntegerField(default=0)  # Add this line for the column field
    row = models.IntegerField(default=0) 
    is_available = models.BooleanField(default=True)

class Reservation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    seats = models.ManyToManyField(Seat)
    """

reservation_system/forms.py
from django import forms
from app.models import User
from .models import ReservationSystemUser, TripSchedule, Message, PackagePayment, CustomerService
from django.contrib.auth.forms import UserCreationForm
import re

#User Forms
class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "password1",
            "password2",
        ]

    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)

        # Adding placeholders for each form field
        self.fields['username'].widget.attrs['placeholder'] = 'Enter your username'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter your email'
        self.fields['password1'].widget.attrs['placeholder'] = 'Enter your password'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm your password'

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class TripScheduleForm(forms.ModelForm):
    class Meta:
        model = TripSchedule
        fields = ['driver', 'origin', 'destination', 'departure_date', 'departure_time', 'estimated_arrival_time', 'price']
        widgets = {
            'departure_date': forms.DateInput(attrs={'type': 'date'}),
            'departure_time': forms.TimeInput(attrs={'type': 'time'}, format='%H:%M'),
            'estimated_arrival_time': forms.TimeInput(attrs={'type': 'time'}, format='%H:%M'),
        
        } 

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['recipient', 'subject', 'body']
        widgets = {
            'body': forms.Textarea(attrs={'placeholder': 'Start typing..', 'rows': 4, 'cols': 50, 'style': 'resize: none;', 'autolink': 'true'}),
        }

class PackagePaymentForm(forms.ModelForm):
    package_id = forms.IntegerField(widget=forms.NumberInput(attrs={'placeholder': 'Enter Package ID', 'class': 'pkg_payment-input'}))
    amount = forms.FloatField(widget=forms.TextInput(attrs={'placeholder': 'Enter required amount', 'class': 'pkg_payment-input'}))
    class Meta:
        model = PackagePayment
        fields = ['initiator','package_id', 'courier', 'sender_name', 'sender_number', 'receiver_name', 'receiver_number', 'amount']
        widgets = {
            'courier': forms.TextInput(attrs={'placeholder': 'Enter Courier of Choice', 'class': 'pkg_payment-input'}), 
            'sender_name': forms.TextInput(attrs={'placeholder': 'Enter Sender`s name', 'class': 'pkg_payment-input'}), 
            'sender_number': forms.TextInput(attrs={'placeholder': 'Enter Sender`s number', 'class': 'pkg_payment-input'}), 
            'receiver_name': forms.TextInput(attrs={'placeholder': 'Enter Receiver`s name', 'class': 'pkg_payment-input'}), 
            'receiver_number': forms.TextInput(attrs={'placeholder': 'Enter Receiver`s name', 'class': 'pkg_payment-input'}), 
        }       

class CustomerServiceMessageForm(forms.ModelForm):
    content = forms.CharField(label='Message', widget=forms.Textarea)
    original_sender_id = forms.IntegerField(widget=forms.HiddenInput(), required=False)

    
    class Meta:
        model =  CustomerService
        fields = [
            'original_sender_id',
            'content'
        ]


class TicketConfirmationForm(forms.Form):
    modal_phone_number = forms.CharField(max_length=20, required=True)

reservation_system/templates/bus_operator_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <style>
        /* Your additional styling goes here */
        .left {
            background: linear-gradient(rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.5)),
                url('{% static "images/bg1.jpg" %}');
            background-size: cover;
        }
        .far {
            position: absolute;
            top: 457px;
            right: 60px;
        }
    </style>
</head>
<body>
    <div class="split-screen">
        <div class="left">
            <section class="copy ">
                <h1 style="color: white; font-size: 100px">Yenda</h1>
                <p>Book Your Next Ticket</p>
            </section>
        </div>
        <div class="right">
            <form method="post" action="{% url 'reservation_system:bus-operator-login' %}">
                {% csrf_token %}
                <section class="copy">
                    <h2>Login</h2>
                    <div class="login-container">
                        <p>Don't have an account? <a href="{% url 'reservation_system:register-bus' %}"><strong>Sign Up</strong></a></p>
                    </div>
                </section>
                <!-- Your form fields go here -->
                <div class="input-container username">
                    <label for="id_username">Username</label>
                    <input id="id_username" name="username" type="text" required>
                </div>
                <div class="input-container password">
                    <label for="id_password">Password</label>
                    <input id="id_password" name="password" type="password" required>
                    <i class="far fa-eye-slash"></i>
                </div>
                <button class="signup-btn" type="submit">Login</button>
                <section class="copy legal">
                    <!-- ... (existing fields) ... -->
                </section>
            </form>
        </div>
    </div>
</body>
</html>

reservation_system/templates/bus_operator_register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Yenda| Get The Best Deals On Intercity Bus Travelling</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <style>
        .left {
            background: linear-gradient(rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.5)),
                url('{% static "images/bg1.jpg" %}');
            background-size: cover;
        }
        
        .error-message {
            color: red;
        }
    </style>
</head>
<body>
    <div class="split-screen">
        <div class="left"> 
            <section class="copy">
                <h1 class="dynamic-txts">
                    <ul>
                        <li><span>Welcome to Yenda</span></li>
                        <li><span>Tuleishani ku Yenda</span></li>
                        <li><span>Kulibonesha ku Yenda</span></li>
                        <li><span>Buloka ku Yenda</span></li>
                    </ul>
                </h1>
                <p>Book Your Ticket Next </p>
            </section>
        </div>
       <div class="right">
        <form method="post" id="busoperatorsignup-form" action="">
            {% csrf_token %}
            {{form.errors}}
            <section class="copy">
                <h2>Sign Up</h2>
                <div class="login-container">
                    <p>Sign up as <a href="{% url 'app:register-user' %}"><strong>Traveller</strong></a></p>
                    <p>Already have an account? <a href="{% url 'app:login' %}"><strong>Log In</strong></a></p>
                </div>
            </section>
            <div class="input-container username">
                <label for="id_username">Bus Operator Name</label>
                <input id="id_username" name="username" type="text" placeholder=" Use a hyphen (-) for spacing ">
                <span class="error-message" id="error-username"></span> <!-- Placeholder for error message -->

            </div>
            <div class="input-container email">
                <label for="id_email">E-mail</label>
                <input id="id_email" name="email" type="email" placeholder="Enter Your Email">
                <span class="error-message" id="error-email"></span> <!-- Placeholder for error message -->
            </div>
            <div class="input-container password">
                <label for="id_password">Enter Password</label>
                <input id="id_password" name="password" type="password" placeholder="Enter Password">
                <span class="error-message" id="error-password"></span> <!-- Placeholder for error message -->
            </div>
            <div class="input-container password">
                <label for="id_password2">Confirm Password</label>
                <input id="id_password2" name="password2" type="password" placeholder="Confirm Password">
                <span class="error-message" id="error-password2"></span> <!-- Placeholder for error message -->
                <i class="far fa-eye-slash"></i>
            </div>
            <div class="input-container cta">
                <label class="checkbox-container">
                    <input type="checkbox">
                    <span class="checkmark"></span>
                    Sign up for email updates.
                </label>
            </div>
            <button class="signup-btn" type="submit">Sign Up</button>
            <section class="copy legal">
                <p><span class="small">By continuing, you agree to accept our <br> <a href="#">Privacy Policy</a> &amp; <a href="#">Terms of service</a></span></p>
            </section>
        </form>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        $(document).ready(function() {
            $("#busoperatorsignup-form").submit(function(e) {
                e.preventDefault(); // Prevent default form submission
    
                // Get form data
                const formData = {
                    username: $("#id_username").val(),
                    email: $("#id_email").val(),
                    password: $("#id_password").val(),
                    password2: $("#id_password2").val(),
                };
    
                // Send AJAX request
                $.ajax({
                    url: "{% url 'reservation_system:bus_operator_registration' %}",
                    type: "POST",
                    contentType: "application/json", // Set content type to JSON
                    data: JSON.stringify(formData), // Convert data to JSON string
                    success: function(response) {
                        console.log("Success:", response);
                        window.location.href = "{% url 'reservation_system:bus_operator_dashboard' %}"; // Redirect to dashboard
                    },
                    error: function(xhr, status, error) {
                        var jsonResponse = JSON.parse(xhr.responseText);
                        var errors = jsonResponse.errors;
                        
                        // Clear previous error messages
                        $(".error-message").text('');
    
                        // Display errors next to the corresponding fields
                        for (var field in errors) {
                            if (errors.hasOwnProperty(field)) {
                                var errorMessage = errors[field][0];
                                $("#error-" + field).text(errorMessage);
                            }
                        }
                    }
                });
            });
        });
    </script>
</body>
</html>

reservation_system/templates/detail_entry.html
<!-- detail_entry.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Yenda| Bus Entry</title>
</head>
<body>

    <h1>Enter Details</h1>

    <form method="post" id="signup-form" action=" ">
        {% csrf_token %}
        <div class="input-container name">
            <label for="id_driver">Driver Name</label><br>
            <input id="id_driver" name="driver" type="text">
            <span class="error-message" id="error-driver"></span> <!-- Placeholder for error message -->
        </div>
        <div class="input-container name">
            <label for="id_origin">Origin</label><br>
            <input id="id_origin" name="origin" type="text">
            <span class="error-message" id="error-origin"></span> <!-- Placeholder for error message -->
        </div>
        <div class="input-container username">
            <label for="id_destination">Destination</label><br>
            <input id="id_destination" name="destination" type="text">
            <span class="error-message" id="error-destination"></span> <!-- Placeholder for error message -->
        </div>
        <div class="input-container email">
            <label for="id_departure_date">Departure Date</label><br>
            <input id="id_departure_date" name="departure_date" type="date">
            <span class="error-message" id="error-departure_date"></span> <!-- Placeholder for error message -->
        </div>
        <div class="input-container password">
            <label for="id_departure_time">Departure Time</label><br>
                <input id="id_departure_time" name="departure_time" type="time">
            <span class="error-message" id="error-departure_time"></span> <!-- Placeholder for error message -->
        </div>
        <div class="input-container password">
            <label for="id_estimated_arrival_time">Estimated Arrival Time</label><br>
            <input id="id_estimated_arrival_time" name="estimated_arrival_time" type="time">
            <span class="error-message" id="error-estimated_arrival_time"></span> <!-- Placeholder for error message -->
        </div>
        <div class="input-container pr">
            <label for="id_price">Price</label><br>
            <input id="id_price" name="price" type="number">
            <span class="error-message" id="error-price"></span> <!-- Placeholder for error message -->
        </div>
        <button type="submit">Submit</button>
    </form>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        $(document).ready(function() {
            $("#signup-form").submit(function(e) {
                e.preventDefault(); // Prevent default form submission
    
                // Get form data
                const formData = {
                    driver: $("#id_driver").val(),
                    origin: $("#id_origin").val(),
                    destination: $("#id_destination").val(),
                    departure_date: $("#id_departure_date").val(),
                    departure_time: $("#id_departure_time").val(),
                    estimated_arrival_time: $("#id_estimated_arrival_time").val(),
                    price: $("#id_price").val(),

                };
    
                // Send AJAX request
                $.ajax({
                    url: "{% url 'reservation_system:trip_detail_entry' %}",
                    type: "POST",
                    contentType: "application/json", // Set content type to JSON
                    data: JSON.stringify(formData), // Convert data to JSON string
                    success: function(response) {
                        console.log("Success:", response);
                        window.location.href = "{% url 'reservation_system:detail_entry' %}"; // Redirect to dashboard
                    },
                    error: function(xhr, status, error) {
                        var jsonResponse = JSON.parse(xhr.responseText);
                        var errors = jsonResponse.errors;
                        
                        // Clear previous error messages
                        $(".error-message").text('');
    
                        // Display errors next to the corresponding fields
                        for (var field in errors) {
                            if (errors.hasOwnProperty(field)) {
                                var errorMessage = errors[field][0];
                                $("#error-" + field).text(errorMessage);
                            }
                        }
                    }
                });
            });
            

        });
    </script>
    
</body>
</html>