Yenda/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app.urls")),
    path('reservation/', include('reservation_system.urls')),
    path('api-token-auth/', obtain_auth_token), #gives us access to token auth

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from .utils import  hash_trip_id, decode_hashed_trip_id

app_name = 'app'

urlpatterns = [

   path("register-user", views.register_user, name="register-user"),
   path("login", views.login_register, name="login"),
   path("logout", views.logoutUser, name="logout"),
   path("", views.dashboard, name="dashboard"),
   path("popular-places", views.popular_places, name="popular places"),
   path('search/', views.search, name='search'),
   path('update_bookmark_status/', views.update_bookmark_status, name='update_bookmark_status'),
   path('bookmarked/', views.bookmarked_trips, name='bookmarked_trips'),
   path('select_tickets/<uuid:trip_id>/', views.select_tickets, name='select_tickets'),
   path('enter_passenger_details/<uuid:trip_id>/', views.enter_passenger_details, name='enter_passenger_details'),
   path('ticket_confirmation/<uuid:trip_id>/', views.ticket_confirmation, name='ticket_confirmation'),
   path('ticket_cancel', views.cancel_confirmation, name ='ticket-cancel'),
   path('ticket_success/<uuid:trip_id>/', views.ticket_success, name='ticket_success'),
   path('tickets', views.tickets, name='tickets'),
   path('update_ticket_active_status/<int:ticket_id>/', views.update_ticket_active_status, name='update_ticket_active_status'),
   path('previous-tickets', views.previous_tickets, name='previous-tickets'),
   path('account-details',views.user_account_details, name = 'account-details'),
   path('about-&-info', views.about_info, name = 'about-info'),
   path('change-name', views.change_name, name='change-name'),
   path('change-profile picture', views.change_profilepic, name='change-profile_pic'),

    
   #Courier Service
   path('courier-search/', views.courier_search, name='courier-search' ),
   path('enter-package-details/', views.enter_package_details, name = 'enter-package-details'),
   path('superuser/messages/', views.superuser_messages, name='superuser_messages'),
   path('inbox/', views.inbox_list, name='inbox-list'),
   path('conversation/<int:sender_id>/', views.conversation, name='conversation'),
   path('check-new-messages/', views.check_new_messages, name='check_new_messages'),
   path('mark-messages-as-read/', views.mark_messages_as_read, name='mark_messages_as_read'),
   path('package-payment/', views.package_payment, name='package-payment'),
   path('courier-receipts/', views.courier_receipts, name='courier-receipts'),
   path('edit/<int:message_id>/', views.edit_message, name='edit_message'),
   path('delete/<int:message_id>/', views.delete_message, name='delete_message'),
   path('toggle_active/<int:receipt_id>/', views.toggle_active, name='toggle_active'),
   path('courier-done/', views.fulfilled_receipts, name='courier-done'),

   
   #Customer Service
   #path('customer-service/message/<int:sender_id>/', views.customer_service_message, name='customer_service_message'),
   path('customer-service/inbox/', views.customer_service_inbox, name='customer_service_inbox'),
   path('submit_message/<int:sender_id>/', views.submit_message, name='submit_message'),


   #Suggestions
   path('submit-suggestion/', views.submit_suggestion, name='submit_suggestion'),


   #Forgot Password
   path('reset_password/',
   auth_views.PasswordResetView.as_view(
      template_name="../templates/registration/reset_password.html",
      success_url = reverse_lazy("app:password_reset_done")
   ), name='reset_password'),

   path('reset_password_sent/',
    auth_views.PasswordResetDoneView.as_view(
    ), name="password_reset_done"),

   path('reset/<uidb64>/<token>/',
    auth_views.PasswordResetConfirmView.as_view(
      template_name="registration/password_reset_confirm.html",
      success_url = reverse_lazy("app:password_reset_complete")
  ), name='password_reset_confirm'),

   path('reset_password_complete/',
    auth_views.PasswordResetCompleteView.as_view(
      template_name="registration/password_reset_complete.html"
    ), name="password_reset_complete"),


# DRF URLS
   path('ticket-confirmation/<uuid:trip_id>', views.TicketConfirmationAPIView.as_view(), name='ticket-confirmation'),

]  

# Add the following line to serve media files during development
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservation_system/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from app.models import User
from django.utils import timezone
import uuid
import qrcode
from io import BytesIO
from django.core.files.base import ContentFile



class ReservationSystemUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='reservationsystemuser')
    email = models.EmailField(null=False, default="")
    total_seats = models.IntegerField(default=0)
    rows = models.IntegerField(default=0)
    columns = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.user}'

class TripSchedule(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, null=False)
    bus_operator = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    driver = models.CharField(max_length=100, default="")
    origin = models.CharField(max_length=100)
    destination = models.CharField(max_length=100)
    departure_date = models.DateField(default=timezone.now)
    departure_time = models.TimeField(default=timezone.now)
    estimated_arrival_time = models.TimeField(default=timezone.now)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    bookmarked = models.BooleanField(default=False)
    
    def __str__(self):
            return f'{self.bus_operator}'

class BuyerDetails(models.Model):
    buyer = models.ForeignKey(User, on_delete=models.CASCADE)
    trip = models.ForeignKey(TripSchedule, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, default="")
    phonenumber = models.CharField(max_length=15, default="")
    confirmed = models.BooleanField(default=False)  # Add this field

class Tickets(models.Model):
    buyer_name = models.ForeignKey(User, on_delete=models.CASCADE)
    buyer_trip = models.ForeignKey(TripSchedule, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, null=True, blank=True)  # Track payment status (e.g., new, paid, failed)
    timestamp = models.DateTimeField(auto_now_add=True)


class Ticket(models.Model):
    ticket_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    buyer = models.ForeignKey(User, on_delete=models.CASCADE)
    trip = models.ForeignKey(TripSchedule, on_delete=models.CASCADE)
    passenger_name = models.CharField(max_length=15, default="", null=True)
    passenger_phonenumber = models.CharField(max_length=15)
    confirmed = models.BooleanField(default=False)
    active = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_used = models.BooleanField(default=False)
    ticket_no = models.CharField(max_length=100, default="")
    
    #QR Code
    qr_code = models.ImageField(upload_to='qr_codes/', blank=True, null=True)

    def save_qr_code(self, ticket_number):
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        qr.add_data(ticket_number)
        qr.make(fit=True)

        qr_code_io = BytesIO()
        qr.make_image(fill_color="black", back_color="white").save(qr_code_io, format='PNG')

        self.qr_code.save(f'qr_code_{self.id}.png', ContentFile(qr_code_io.getvalue()), save=False)
        super().save()

    def __str__(self):
        return f"Ticket ID: {self.ticket_id}, Passenger: {self.passenger_name}, Trip: {self.trip}"



# ===== COURIER SERVICES =====
class PackageDetails(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    item_name = models.CharField(max_length=100, default="")
    length =  models.DecimalField(max_digits=8, decimal_places=2)
    width =   models.DecimalField(max_digits=8, decimal_places=2)
    height = models.DecimalField(max_digits=8, decimal_places=2)
    weight = models.DecimalField(max_digits=8, decimal_places=2)
    item_quantity = models.IntegerField(default=1)
    fragile_item = models.BooleanField(default=False, null=True, blank=True)
    item_category = models.CharField(max_length=100, default="")
    item_description = models.TextField()

class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_messages')
    recipient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_messages')
    subject = models.CharField(max_length=100)
    body = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.subject} - From: {self.sender.username} To: {self.recipient.username}"

class PackagePayment(models.Model):
    initiator = models.ForeignKey(User, on_delete=models.CASCADE,null=True, related_name='package_payment')
    pesapal_transaction_tracking_id = models.CharField(max_length=100, default='', null=True, blank=True)
    package_id = models.IntegerField( default=0)
    courier = models.CharField(max_length=20, default="")
    sender_name = models.CharField(max_length=20, default="")
    sender_number = models.CharField(max_length=20, default="")
    receiver_name =  models.CharField(max_length=20, default="")
    receiver_number =models.CharField(max_length=20, default="")
    amount = models.FloatField(default=0)
    status = models.CharField(max_length=20, null=True, blank=True)  # Track payment status (e.g., new, paid, failed)
    is_active = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    qr_code = models.ImageField(upload_to='courier receipt-qr_codes/', blank=True, null=True)

    def save_qr_code(self, package_id):
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        qr.add_data(package_id)
        qr.make(fit=True)

        qr_code_io = BytesIO()
        qr.make_image(fill_color="black", back_color="white").save(qr_code_io, format='PNG')

        self.qr_code.save(f'qr_code_{self.id}.png', ContentFile(qr_code_io.getvalue()), save=False)
        super().save()


class CustomerService(models.Model):
    sender = models.ForeignKey(User, related_name='customer_service_sent_messages', on_delete=models.CASCADE, default=None)
    receiver = models.ForeignKey(User, related_name='customer_service_received_messages', on_delete=models.CASCADE, default=None)
    content = models.TextField(default='')
    read = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"From {self.sender.username} to {self.receiver.username}: {self.content}"


class Suggestion(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)  # Optional user association
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)  # Automatic timestamp
  
    def __str__(self):
        return f"{self.description} - {self.user}"




































    

    """
    # New fields to store the number of rows and columns
    rows = models.IntegerField(default=0)
    columns = models.IntegerField(default=0)

# models.py
class Seat(models.Model):
    bus_operator = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    trip_schedule = models.ForeignKey(TripSchedule, on_delete=models.CASCADE, null=True)
    booked_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='booked_seats', null=True)
    seat_number = models.CharField(max_length=10)
    column = models.IntegerField(default=0)  # Add this line for the column field
    row = models.IntegerField(default=0) 
    is_available = models.BooleanField(default=True)

class Reservation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    seats = models.ManyToManyField(Seat)
    """

app/templates/enter_package_details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Yenda| Enter Package Details{% endblock %}</title> 
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <style>
    .header-container {
        background: rgb(219, 218, 218);
        text-align: center;
        margin-bottom: 20px;
    }

    .header-container .date {
        font-weight: bold;
        font-size: 20px;
        margin-bottom: 10px;
    }

    .header-container .result-container {
        font-size: 15px;
    }

    .header-container .result-container .result-text {
        display: flex;
        flex-direction: row;
        gap: 10px;
        justify-content: center;
        margin-bottom: 10px;
    }

    .header-container .result-container .result-text .fa {
            font-weight: lighter;
    }

    .header-title {
        text-align: center;
    }

    .package-details-form {
        background-color: rgb(230, 228, 228);
        margin: auto;
        width: 100%;
        height: 100%;
        border-radius: 20px;
    }

    #confirm-pkg-btn {
        border-radius: 20px;
        margin-left: 900px;
        margin-bottom: 20px;
        width: 200px;
        padding: 10px 20px;
        background-color: var(--primary-color);
        color: var(--border-color);
        cursor: pointer;
        border: none;
        font-size: 16px;
        cursor: pointer;
    }

    #confirm-pkg-btn:hover {
        background-color: var(--primary-color);
        color: var(--text-color);
       
    }

    label {
        color: var(--primary-color);
        margin-left: 10px;
    }

    .item-name {
        border-radius: 5px;
        width: 450px;
        height: 30px;
        margin-left: 20px;
        margin-bottom: 10px;
    }

    .item-name-l,
    .item-name-w,
    .item-name-h {
        height: 30px;
        width: 250px;
    }

    .description-input {
        width: 450px;
        margin-left: 20px;
        margin-bottom: 10px;

    }

    ::-webkit-input-placeholder {
        margin-left: 10px;
    }

    :-moz-placeholder {
        margin-left: 10px;
    }

    .unit {
        position: relative;
        font-style: italic;
        color: var(--text-color);
        right: 30px;
      
    }

    .item .lwh-container {
        display: flex;
        flex-direction: row;
        margin-top: 50px;
        gap: 150px;
    }

    .weight-item-quantity-container {
        display: flex;
        flex-direction: row;
        margin-top: 50px;
        gap: 250px;
    }

    .fragile-category-container {
        display: flex;
        flex-direction: row;
        margin-top: 50px;
        gap: 568px;
    }

    .item-desc-btn {
        display: flex;
        flex-direction: row;
        margin-top: 50px;
        gap: 100px;
    }

    .unit-kg {
        position: relative;
        font-style: italic;
        color: var(--text-color);
        right: 30px;
    }

    @media (max-width: 780px) {
        .item-name {
            border-radius: 5px;
            width: 330px;
            height: 30px;
            margin-left: 20px;
            margin-bottom: 10px;
        }

        .item .lwh-container {
            display: flex;
            flex-direction: column;
            margin-top: 50px;
            gap: 50px;
        }

        .weight-item-quantity-container {
            display: flex;
            flex-direction: column;
            margin-top: 50px;
            gap: 10px;
        }

        .fragile-category-container {
            display: flex;
            flex-direction: column;
            margin-top: 50px;
            gap: 50px;
        }

        .description-input {
            width: 300px;
            margin-left: 20px;
            margin-bottom: 10px;
        }

        #confirm-pkg-btn {
            margin-left: 80px;
            margin-bottom: 20px;
            width: 200px;
        }

        .unit-kg {
            left: 89%;
            bottom: 38px;
        }


    }
    </style>
</head>

<body>

    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}

    <div class="header-container">
        <div class="result-container">
            <div class="result-text">
                <span id="displayCurrentLocation"></span> <i class="fas fa-arrow-right"></i> <span id="displayDestination"></span>
            </div>
        </div> 
    </div>
    <h3 class="header-title"> Enter Package Details </h3>
        <p style="text-align: center;"><strong>Note:</strong> Enter Correct/Estimated details for accurate pricing..</p>
                    
            <div class="package-details-form">
                <form id="package-details-form" method="post" action="{% url 'app:enter-package-details' %}">
                    {% csrf_token %}
                    {{ form.errors }}
                    <!-- Include hidden fields for currentLocation and destination -->
                    <input type="hidden" name="current_location" id="currentLocationInput">
                    <input type="hidden" name="destination" id="destinationInput">
                        <br>

                        <div class="item lwh-container">
                            <label style="display: block; margin-bottom: 10px;" for="id_item_name">Item Name:</label>
                            {{form.item_name}}

                            <div class="lwh-container">
                                <label style="display: block; margin-bottom: 10px;" for="id_length">Length: {{ form.length }}<span class="unit">cm</span></label>
                                
                            
                                <label style="display: block; margin-bottom: 10px;" for="id_width">Width: {{ form.width }}<span class="unit">cm</span></label>
                                
                                <label style="display: block; margin-bottom: 10px;" for="id_height">Height: {{ form.height }}<span class="unit">cm</span>
                                </label>
                            </div>
                        </div>

                        <div class="weight-item-quantity-container">
                            <label style="display: block; margin-bottom: 10px;" for="id_weight">Weight:<br><br> {{ form.weight }}<span class="unit-kg">kg</span></label>
                            
                        
                            <label style="display: block; margin-bottom: 10px;" for="id_item_quantity">Item Quantity:<br><br>  {{ form.item_quantity }}</label>
                           
                        </div>
                        
                        <div class="fragile-category-container">
                            <label style="display: block; margin-bottom: 10px;" for="id_fragile_item">Fragile Item: {{ form.fragile_item }}</label>
                             
                            <label style="display: block; margin-bottom: 10px;" for="id_item_category">Item Category: <br><br> {{ form.item_category }}</label>

                        </div>
                        
                       
                        <label style="display: block; margin-top: 50px; margin-bottom: 10px;" for="id_item_description">Item Description:<br><br> {{ form.item_description }}</label>
                        

                        <button  type="submit" id="confirm-pkg-btn">Submit</button>
                        
             </div>
            
        </form>
    </div>
    


    <script>
        // Retrieve values from localStorage
        var currentLocation = localStorage.getItem('currentLocation');
        var destination = localStorage.getItem('destination');
       

        // Display values in the designated spans
        document.getElementById('displayCurrentLocation').innerText = currentLocation;
        document.getElementById('displayDestination').innerText = destination;

        // Set values of hidden input fields
        document.getElementById('currentLocationInput').value = currentLocation;
        document.getElementById('destinationInput').value = destination
    </script>

    
    <!-- JavaScript to handle Enter key press -->
    <script>
        // Function to show confirm dialog when "Submit" button is clicked
        document.getElementById('confirm-pkg-btn').addEventListener('click', function(event) {
            event.preventDefault();
            if (confirm('Enter correct/Estimated details for accurate pricing..')) {
                document.getElementById('package-details-form').submit();
            }
        });
    </script>
    

</body>
</html>
{% endblock %}

app/templates/enter_passenger_details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<title>{% block title %}Yenda| Get first ticket FREE!{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}">
<style>
    .background-container {
        width: 100%;
        height: 100%;
        overflow: hidden;
    }

    .background-image {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-size: cover;
        background-position: center;
        filter: blur(5px); /* Add blur effect to the background image */
        z-index: -1;
    }

    .container {
        display: flex;
        justify-content: center; /* Center items horizontally */
    }

    .passenger-details-container {
        margin-top: 10px;
    }

    .passenger-details-button {
        border-radius: 20px;
        padding: 10px 20px;
        background-color: var(--primary-color);
        color: var(--border-color);
        cursor: pointer;
        border: none;
        font-size: 16px;
        cursor: pointer;
        
    }

    .passenger-details-button:hover {
        color: var(--text-color);
    }

    .container .passenger-details-container .passenger-details-form {
        background-color: rgb(230, 228, 228);
        border-radius: 20px;
        padding: 20px 30px;
    }
</style>


    <div class="container">
        <div class="passenger-details-container">
            
            <div class="passenger-details-form">
                <form method="post" action="{% url 'app:enter_passenger_details' trip.id %}">
                    <h3 style="color: var(--text-color);">Enter Passenger Details</h3><br>
                    {% csrf_token %}
                    {{ formset.management_form }}

                    {% for form in formset %}
                    <strong style="display: block; margin-bottom: 10px; color: var(--primary-color);" >Passenger {{forloop.counter}}</strong>
                    <label style="display: block; margin-bottom: 10px;"  for="id_name"><i class="fas fa-user"></i>
                        Name</label>
                    {{ form.name}}<br><br>

                    <label style="display: block; margin-bottom: 10px;"  for="id_phonenumber"><i class="fas fa-phone"></i>
                        Phone Number</label>
                    {{ form.phonenumber}}<br><br>
                    {% endfor %}

                    <input type="submit" value="Submit"  class="passenger-details-button">
                </form>
            </div>
        </div>
    </div>
</div>



{% endblock %}

app/templates/tickets.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Yenda| Tickets{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}">

    <style>
        li{
            list-style: none;
        }
        
        .container {
            display: flex;
            justify-content: center; /* Center items horizontally */
        }

        .ticket {
            position: relative;
            width: 700px; /* Adjust width as needed */
            padding: 20px;
            background-color: #fff;
            border: 3px dotted #000;
            border-radius: 10px;
            overflow: hidden;
            margin-bottom: 20px;
            background-color: var(--secondary-color);
            color: #fff;
        
        }

        .ticket:before,
        .ticket:after {
            content: '';
            position: absolute;
            top: 50%; /* Position at the vertical center */
            width: 40px; /* Adjust size of circles */
            height: 40px; /* Adjust size of circles */
            background-color: #fff;
            border: 2px solid #000;
            border-radius: 50%; /* Make circles */
            transform: translateY(-50%); /* Center vertically */
        }

        .ticket:before {
            left: -22px; /* Adjust horizontal position */
        }

        .ticket:after {
            right: -22px; /* Adjust horizontal position */
        }

        .ticket-content {
            /* Adjust padding to accommodate the circles */
            padding: 10px;
        }

        .trip-time-container{
            display: flex;
            flex-direction: row;
            gap: 200px;
        }

        .trip-origin-destination-container{
            display: flex;
            flex-direction: row;
            gap: 200px;
        }

        .bus-operator-ticket{
            display: flex;
            flex-direction: row;
            gap: 300px;
        }

        .ticket-logo img{
            width: 50px;
            height: 50px;
            margin-bottom: 20px;
        }

        a{
            color: #000;
            text-decoration: none;
        }

        a:hover {
            color: rgb(255, 207, 207);
            text-decoration: none;
        }

        .arrived-button{
            cursor: pointer;
            border-radius: 20px;
            padding: 0px 5px 0px 5px;
        }

        .arrived-button:hover {
           color: var(--secondary-color);
        }

        
        .ticket-history-button-container{
            display: flex;
            flex-direction: row-reverse;
            gap: 5px;
            justify-content: center;
        }

        .history-btn {
            border-radius: 20px;
            padding: 0px 5px 0px 5px;
            cursor: pointer;
            
        }

        .history-btn:hover {
            color: var(--primary-color);
        }

        .ticket-btn-container {
            display: flex;
            flex-direction: row;
            gap: 451px;
        }

        @media (max-width: 780px) {
            .container {
                position: relative;
                display: flex;
                flex-direction: row;
                box-sizing: border-box;
                border-radius: 8px;
                margin-top: 20px;
                gap: 50px;
                right: 30px;
                width: 370px;
                height: auto;
                margin: 0 auto;
                margin-bottom: 0;
            }

            .ticket {
                width: 370px;
            }

            .bus-operator-ticket {
                gap: 88px;
            }

            .trip-origin-destination-container {
                gap: 60px;
            }

			.trip-time-container {
				gap: 46px;
			}

            .ticket-btn-container {
                display: flex;
                flex-direction: row;
                gap: 97px;
            }
            
            .qrcode-container {
                width: 350px;
                right: 20px;
            }
    }
    </style>
</head>

<body>
    <div class="ticket-history-button-container">
        <a  id="previousTicketsButton"><button type="button" class="history-btn" style="background-color: white;">Previous Tickets</button></a><br><br>
        <a href="{% url 'app:tickets' %}"><button type="button" class="history-btn" style="color: var(--box1-color);">Active Tickets</button></a>
    </div>
    <ul>
        {% for ticket in tickets %}
            <li>
                    <div class="container">
                        <div class="ticket">
								<div class="ticket-content">
									<div class="ticket-logo"><img src="{% static 'images/logo.png' %}" alt="Logo"></div>
									<div class="bus-operator-ticket">
										<p><strong style="color: #1848a0;  font-weight: bold ;">Bus Operator:</strong><span style="color: #000;"><br> {{ ticket.trip.bus_operator}}</span></p>
										<p><strong style="color: #1848a0; font-weight: bold">Ticket ID:</strong><span style="color: #000;"><br> {{ ticket.id}}</span></p>
									</div>
								
									<p><strong style="color: #1848a0; font-weight: bold">Passenger Name:</strong><span style="color: #000;"><br> {{ ticket.passenger_name}}</span></p>
									<div class="trip-origin-destination-container">
										<p><strong style="color: #1848a0; font-weight: bold">Origin:</strong><span style="color: #000;"><br> {{ ticket.trip.origin}}</span></p>
										<span>&#128652;</span>
										<p><strong style="color: #1848a0; font-weight: bold">Destination:</strong><span style="color: #000;"><br> {{ ticket.trip.destination}}</span></p>
									</div>
								<br>
									<div class="trip-time-container">
										<p><strong style="color: #1848a0; font-weight: bold">Trip Date:</strong><span style="color: #000;"><br> {{ ticket.trip.departure_date}}</span> </p>
										<p><strong style="color: #1848a0; font-weight: bold  ">Departure Time:</strong><span style="font-weight: bold; font-size: 20px; color: #000;"><br> {{ ticket.trip.departure_time }}</span></p>
									</div>
									
									<div class="ticket-btn-container">
                                        <a href="{% url 'app:update_ticket_active_status' ticket.id %}?button_clicked=true"><button type="button" class="arrived-button" id="arrived-button">Arrived</button></a>
                                        <a href="{% url 'app:ticket_success' ticket.trip.id %}" ><button type="button" class="arrived-button"> More Details </button></a>
                                    </div>
							</div>
                        </div>
                    </div>
            </li>
        {% endfor %}
    </ul> 


 
</body>
<script>
    document.getElementById("previousTicketsButton").addEventListener("click", function(event) {
      event.preventDefault();
      window.location.href = "{% url 'app:previous-tickets' %}";

      console.log("click"); // Print "click" to the console on button click

    });
  </script>
</html>
{% endblock %}